import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  userGuideSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'manual/user-manual',
        'manual/index',
        'manual/installation',
        'manual/basic-usage',
        'manual/paraview-rendering',
        'manual/blender-rendering',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Topics',
      collapsed: true,
      items: [
        'manual/cfddem-simulation',
        'manual/tips/read-restart',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: true,
      items: [
        'manual/developer-manual',
        'manual/dev-design/utils',
        'manual/dev-design/fields',
        'manual/dev-design/parsim',
        'manual/dev-pybind-styles',
        'manual/docker-hpc',
        'manual/computer-tips',
      ],
    },
    {
      type: 'category',
      label: 'Theory',
      collapsed: true,
      items: [
        'manual/dem-wiki',
        'manual/dem-basics',
        'manual/discrete-to-continuum',
        'manual/particle-models',
      ],
    },
  ],

  /** Python API only — use the header “Docs” item to open the manual; avoids mixing manual entries here. */
  pythonApiSidebar: [{type: 'autogenerated', dirName: 'python-api'}],

  examplesSidebar: [
    'examples/index',
    'examples/random-packing',
    'examples/blade-mixing',
    'examples/granular-mixing',
    'examples/triaxial-compression',
    'examples/angle-of-repose',
  ],

  gallerySidebar: [
    'gallery/animations',
    'gallery/snapshots',
  ],

  downloadSidebar: [{type: 'autogenerated', dirName: 'download'}],

  aboutSidebar: ['about/index'],
};

export default sidebars;
