import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: 'category',
      label: 'User manual',
      link: {type: 'doc', id: 'documentation/user-manual'},
      collapsed: false,
      items: [
        'documentation/installation',
        'documentation/basic-usage',
        'documentation/computer-tips',
        'documentation/paraview-rendering',
        'documentation/blender-rendering',
        'documentation/cfddem-simulation',
        {
          type: 'category',
          label: 'Tips',
          collapsed: true,
          items: ['documentation/tips/read-restart'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer manual',
      link: {type: 'doc', id: 'documentation/developer-manual'},
      collapsed: true,
      items: [
        'documentation/dev-pybind-styles',
        'documentation/dem-basics',
        'documentation/discrete-to-continuum',
        'documentation/particle-models',
        'documentation/docker-hpc',
      ],
    },
    {
      type: 'category',
      label: 'Python API',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'documentation/python-api'}],
    },
    'documentation/dem-wiki',
  ],

  examplesSidebar: [
    'examples/index',
    'examples/random-packing',
    'examples/blade-mixing',
    'examples/triaxial-compression',
    'examples/angle-of-repose',
    'examples/granular-mixing',
  ],

  gallerySidebar: [
    'gallery/animations',
    'gallery/snapshots',
  ],

  downloadSidebar: [{type: 'autogenerated', dirName: 'download'}],

  aboutSidebar: [
    'about/help-and-support',
    'about/publications',
    'about/acknowledgement',
  ],
};

export default sidebars;
