var dir_b957ce71d4cec3aa1e6b9f7647e1edd6 =
[
    [ "cgal_wrapper.cpp", "cgal__wrapper_8cpp.html", null ],
    [ "cgal_wrapper.hpp", "cgal__wrapper_8hpp.html", "cgal__wrapper_8hpp" ],
    [ "cork_wrapper.cpp", "cork__wrapper_8cpp.html", "cork__wrapper_8cpp" ],
    [ "cork_wrapper.hpp", "cork__wrapper_8hpp.html", "cork__wrapper_8hpp" ],
    [ "distribution.hpp", "distribution_8hpp.html", "distribution_8hpp" ],
    [ "distribution_uniform.hpp", "distribution__uniform_8hpp.html", "distribution__uniform_8hpp" ],
    [ "eigen_wrapper.cpp", "eigen__wrapper_8cpp.html", "eigen__wrapper_8cpp" ],
    [ "eigen_wrapper.hpp", "eigen__wrapper_8hpp.html", "eigen__wrapper_8hpp" ],
    [ "igl_wrapper.cpp", "igl__wrapper_8cpp.html", "igl__wrapper_8cpp" ],
    [ "igl_wrapper.hpp", "igl__wrapper_8hpp.html", "igl__wrapper_8hpp" ],
    [ "level_set_function.cpp", "level__set__function_8cpp.html", null ],
    [ "level_set_function.hpp", "level__set__function_8hpp.html", "level__set__function_8hpp" ],
    [ "mini_map.hpp", "mini__map_8hpp.html", "mini__map_8hpp" ],
    [ "sdf_calculator.cpp", "sdf__calculator_8cpp.html", "sdf__calculator_8cpp" ],
    [ "sdf_calculator.hpp", "sdf__calculator_8hpp.html", "sdf__calculator_8hpp" ],
    [ "spherical_voronoi.cpp", "spherical__voronoi_8cpp.html", null ],
    [ "spherical_voronoi.hpp", "spherical__voronoi_8hpp.html", "spherical__voronoi_8hpp" ],
    [ "stl_model.cpp", "stl__model_8cpp.html", null ],
    [ "stl_model.hpp", "stl__model_8hpp.html", "stl__model_8hpp" ],
    [ "stl_reader.cpp", "stl__reader_8cpp.html", null ],
    [ "stl_reader.hpp", "stl__reader_8hpp.html", "stl__reader_8hpp" ],
    [ "utils_distributions.hpp", "utils__distributions_8hpp.html", "utils__distributions_8hpp" ],
    [ "utils_io.cpp", "utils__io_8cpp.html", null ],
    [ "utils_io.hpp", "utils__io_8hpp.html", "utils__io_8hpp" ],
    [ "utils_macros.hpp", "utils__macros_8hpp.html", "utils__macros_8hpp" ],
    [ "utils_math.cpp", "utils__math_8cpp.html", null ],
    [ "utils_math.hpp", "utils__math_8hpp.html", "utils__math_8hpp" ],
    [ "utils_operators.cpp", "utils__operators_8cpp.html", "utils__operators_8cpp" ],
    [ "utils_operators.hpp", "utils__operators_8hpp.html", "utils__operators_8hpp" ],
    [ "voronoi.cpp", "voronoi_8cpp.html", null ],
    [ "voronoi.hpp", "voronoi_8hpp.html", "voronoi_8hpp" ],
    [ "wscvt_sampler.hpp", "wscvt__sampler_8hpp.html", "wscvt__sampler_8hpp" ]
];