var hierarchy =
[
    [ "netdem::BondedSpheres", "classnetdem_1_1_bonded_spheres.html", null ],
    [ "netdem::BondedVoronois", "classnetdem_1_1_bonded_voronois.html", null ],
    [ "netdem::BondEntry", "classnetdem_1_1_bond_entry.html", null ],
    [ "netdem::BondEntryData", "structnetdem_1_1_bond_entry_data.html", null ],
    [ "netdem::BondEntryParser", "classnetdem_1_1_bond_entry_parser.html", null ],
    [ "netdem::BondGeometries", "classnetdem_1_1_bond_geometries.html", null ],
    [ "netdem::BondSolverPP", "classnetdem_1_1_bond_solver_p_p.html", null ],
    [ "netdem::BondSolverPW", "classnetdem_1_1_bond_solver_p_w.html", null ],
    [ "netdem::Cell", "classnetdem_1_1_cell.html", null ],
    [ "netdem::CellManager", "classnetdem_1_1_cell_manager.html", null ],
    [ "netdem::CGALWrapper", "classnetdem_1_1_c_g_a_l_wrapper.html", null ],
    [ "netdem::CollisionEntry", "classnetdem_1_1_collision_entry.html", null ],
    [ "netdem::CollisionEntryData", "structnetdem_1_1_collision_entry_data.html", null ],
    [ "netdem::CollisionEntryParser", "classnetdem_1_1_collision_entry_parser.html", null ],
    [ "netdem::CollisionGeometries", "classnetdem_1_1_collision_geometries.html", null ],
    [ "netdem::CollisionSolverPP", "classnetdem_1_1_collision_solver_p_p.html", [
      [ "netdem::SolverANNPP", "classnetdem_1_1_solver_a_n_n_p_p.html", null ],
      [ "netdem::SolverBooleanPP", "classnetdem_1_1_solver_boolean_p_p.html", null ],
      [ "netdem::SolverGJKPP", "classnetdem_1_1_solver_g_j_k_p_p.html", null ],
      [ "netdem::SolverSDFPP", "classnetdem_1_1_solver_s_d_f_p_p.html", null ],
      [ "netdem::SolverSphereSphere", "classnetdem_1_1_solver_sphere_sphere.html", null ]
    ] ],
    [ "netdem::CollisionSolverPW", "classnetdem_1_1_collision_solver_p_w.html", [
      [ "netdem::SolverANNPPlane", "classnetdem_1_1_solver_a_n_n_p_plane.html", null ],
      [ "netdem::SolverANNPW", "classnetdem_1_1_solver_a_n_n_p_w.html", null ],
      [ "netdem::SolverBooleanPW", "classnetdem_1_1_solver_boolean_p_w.html", null ],
      [ "netdem::SolverGJKPW", "classnetdem_1_1_solver_g_j_k_p_w.html", null ],
      [ "netdem::SolverSDFPW", "classnetdem_1_1_solver_s_d_f_p_w.html", null ],
      [ "netdem::SolverSpherePlane", "classnetdem_1_1_solver_sphere_plane.html", null ],
      [ "netdem::SolverSphereTriangle", "classnetdem_1_1_solver_sphere_triangle.html", null ]
    ] ],
    [ "netdem::Command", "classnetdem_1_1_command.html", [
      [ "netdem::CommandCreate", "classnetdem_1_1_command_create.html", null ]
    ] ],
    [ "netdem::ContactForces", "classnetdem_1_1_contact_forces.html", null ],
    [ "netdem::ContactModel", "classnetdem_1_1_contact_model.html", [
      [ "netdem::HertzMindlin", "classnetdem_1_1_hertz_mindlin.html", null ],
      [ "netdem::LinearSpring", "classnetdem_1_1_linear_spring.html", null ],
      [ "netdem::ParallelBond", "classnetdem_1_1_parallel_bond.html", null ],
      [ "netdem::VolumeBased", "classnetdem_1_1_volume_based.html", null ]
    ] ],
    [ "netdem::ContactModelFactory", "classnetdem_1_1_contact_model_factory.html", null ],
    [ "netdem::ContactPP", "classnetdem_1_1_contact_p_p.html", null ],
    [ "netdem::ContactPPData", "structnetdem_1_1_contact_p_p_data.html", null ],
    [ "netdem::ContactPPParser", "classnetdem_1_1_contact_p_p_parser.html", null ],
    [ "netdem::ContactPW", "classnetdem_1_1_contact_p_w.html", null ],
    [ "netdem::ContactPWData", "structnetdem_1_1_contact_p_w_data.html", null ],
    [ "netdem::ContactPWParser", "classnetdem_1_1_contact_p_w_parser.html", null ],
    [ "netdem::ContactSolverFactory", "classnetdem_1_1_contact_solver_factory.html", null ],
    [ "netdem::ContactSolverSettings", "classnetdem_1_1_contact_solver_settings.html", null ],
    [ "netdem::CorkWrapper", "classnetdem_1_1_cork_wrapper.html", null ],
    [ "netdem::DEMFragment", "classnetdem_1_1_d_e_m_fragment.html", null ],
    [ "netdem::DEMObjectPool", "classnetdem_1_1_d_e_m_object_pool.html", null ],
    [ "netdem::DEMProfiler", "classnetdem_1_1_d_e_m_profiler.html", null ],
    [ "netdem::DEMSolver", "classnetdem_1_1_d_e_m_solver.html", null ],
    [ "netdem::Distribution", "classnetdem_1_1_distribution.html", [
      [ "netdem::UniformDistribution", "classnetdem_1_1_uniform_distribution.html", null ]
    ] ],
    [ "netdem::Domain", "classnetdem_1_1_domain.html", null ],
    [ "netdem::DomainManager", "classnetdem_1_1_domain_manager.html", null ],
    [ "netdem::DomainSplittor", "classnetdem_1_1_domain_splittor.html", [
      [ "netdem::LevelSetSplittor", "classnetdem_1_1_level_set_splittor.html", null ],
      [ "netdem::TetMeshSplittor", "classnetdem_1_1_tet_mesh_splittor.html", null ]
    ] ],
    [ "netdem::EigenWrapper", "classnetdem_1_1_eigen_wrapper.html", null ],
    [ "netdem::FEMSimulator", "classnetdem_1_1_f_e_m_simulator.html", null ],
    [ "netdem::GeneralNet", "classnetdem_1_1_general_net.html", null ],
    [ "netdem::GoldenSpiralSampler", "classnetdem_1_1_golden_spiral_sampler.html", null ],
    [ "netdem::IGLWrapper", "classnetdem_1_1_i_g_l_wrapper.html", null ],
    [ "netdem::InputProcessor", "classnetdem_1_1_input_processor.html", null ],
    [ "netdem::IO", "classnetdem_1_1_i_o.html", null ],
    [ "netdem::LevelSetFunction", "classnetdem_1_1_level_set_function.html", [
      [ "netdem::LevelSet", "classnetdem_1_1_level_set.html", null ],
      [ "netdem::LevelSetSplittor", "classnetdem_1_1_level_set_splittor.html", null ]
    ] ],
    [ "netdem::Math", "classnetdem_1_1_math.html", null ],
    [ "netdem::webgpu::Math", "classnetdem_1_1webgpu_1_1_math.html", null ],
    [ "netdem::Membrane", "classnetdem_1_1_membrane.html", [
      [ "netdem::MembraneWall", "classnetdem_1_1_membrane_wall.html", null ]
    ] ],
    [ "netdem::MiniMap< T_key, T_val >", "classnetdem_1_1_mini_map.html", null ],
    [ "netdem::MiniMap< int, netdem::ContactModel * >", "classnetdem_1_1_mini_map.html", null ],
    [ "netdem::MiniMap< int, VecXT< Vec3d > >", "classnetdem_1_1_mini_map.html", null ],
    [ "netdem::MiniMap< std::string, double >", "classnetdem_1_1_mini_map.html", null ],
    [ "netdem::MLPackUtils", "classnetdem_1_1_m_l_pack_utils.html", null ],
    [ "netdem::Modifier", "classnetdem_1_1_modifier.html", [
      [ "netdem::DataDumper", "classnetdem_1_1_data_dumper.html", null ],
      [ "netdem::ExternalForce", "classnetdem_1_1_external_force.html", null ],
      [ "netdem::Gravity", "classnetdem_1_1_gravity.html", null ],
      [ "netdem::MembraneWall", "classnetdem_1_1_membrane_wall.html", null ],
      [ "netdem::ParticleGroup", "classnetdem_1_1_particle_group.html", [
        [ "netdem::BreakageAnalysis", "classnetdem_1_1_breakage_analysis.html", null ],
        [ "netdem::BreakageAnalysisPD", "classnetdem_1_1_breakage_analysis_p_d.html", null ],
        [ "netdem::DeformationAnalysis", "classnetdem_1_1_deformation_analysis.html", null ],
        [ "netdem::ParticleEnergyEvaluator", "classnetdem_1_1_particle_energy_evaluator.html", null ],
        [ "netdem::ParticleStressEvaluator", "classnetdem_1_1_particle_stress_evaluator.html", null ]
      ] ],
      [ "netdem::ParticleMotionControl", "classnetdem_1_1_particle_motion_control.html", null ],
      [ "netdem::UnbalancedForceRatioEvaluator", "classnetdem_1_1_unbalanced_force_ratio_evaluator.html", null ],
      [ "netdem::WallGroup", "classnetdem_1_1_wall_group.html", [
        [ "netdem::WallMotionControl", "classnetdem_1_1_wall_motion_control.html", null ],
        [ "netdem::WallMotionIntegrator", "classnetdem_1_1_wall_motion_integrator.html", null ],
        [ "netdem::WallServoControl", "classnetdem_1_1_wall_servo_control.html", null ]
      ] ]
    ] ],
    [ "netdem::ModifierManager", "classnetdem_1_1_modifier_manager.html", null ],
    [ "netdem::MPIDataDefine", "classnetdem_1_1_m_p_i_data_define.html", null ],
    [ "netdem::MPIManager", "classnetdem_1_1_m_p_i_manager.html", null ],
    [ "netdem::NeighPofP", "classnetdem_1_1_neigh_pof_p.html", null ],
    [ "netdem::NeighPofW", "classnetdem_1_1_neigh_pof_w.html", null ],
    [ "netdem::NeighWofP", "classnetdem_1_1_neigh_wof_p.html", null ],
    [ "netdem::PackGenerator", "classnetdem_1_1_pack_generator.html", null ],
    [ "netdem::Pair< T_key, T_val >", "structnetdem_1_1_pair.html", null ],
    [ "netdem::PairHash", "structnetdem_1_1_pair_hash.html", null ],
    [ "netdem::Particle", "classnetdem_1_1_particle.html", [
      [ "netdem::DeformableParticle", "classnetdem_1_1_deformable_particle.html", null ]
    ] ],
    [ "netdem::ParticleData", "structnetdem_1_1_particle_data.html", null ],
    [ "netdem::ParticleDataGPU", "structnetdem_1_1_particle_data_g_p_u.html", null ],
    [ "netdem::ParticleEnergy", "structnetdem_1_1_particle_energy.html", null ],
    [ "netdem::ParticleParser", "classnetdem_1_1_particle_parser.html", null ],
    [ "netdem::ParticleParserGPU", "classnetdem_1_1_particle_parser_g_p_u.html", null ],
    [ "netdem::PeriDigmBlock", "classnetdem_1_1_peri_digm_block.html", null ],
    [ "netdem::PeriDigmBoundaryCondition", "classnetdem_1_1_peri_digm_boundary_condition.html", null ],
    [ "netdem::PeriDigmDamageModel", "classnetdem_1_1_peri_digm_damage_model.html", null ],
    [ "netdem::PeriDigmDEMCoupler", "classnetdem_1_1_peri_digm_d_e_m_coupler.html", null ],
    [ "netdem::PeriDigmDiscretization", "classnetdem_1_1_peri_digm_discretization.html", null ],
    [ "netdem::PeriDigmMaterial", "classnetdem_1_1_peri_digm_material.html", null ],
    [ "netdem::PeriDigmSettings", "classnetdem_1_1_peri_digm_settings.html", null ],
    [ "netdem::PeriDigmSimulator", "classnetdem_1_1_peri_digm_simulator.html", null ],
    [ "netdem::PeriDigmStrength", "classnetdem_1_1_peri_digm_strength.html", null ],
    [ "netdem::webgpu::PrefixSum", "classnetdem_1_1webgpu_1_1_prefix_sum.html", null ],
    [ "netdem::Math::Quaternion", "classnetdem_1_1_math_1_1_quaternion.html", null ],
    [ "netdem::webgpu::RadixSort", "classnetdem_1_1webgpu_1_1_radix_sort.html", null ],
    [ "netdem::RandomEngine", "classnetdem_1_1_random_engine.html", null ],
    [ "netdem::RegressionNet", "classnetdem_1_1_regression_net.html", null ],
    [ "netdem::webgpu::ResourceManager", "classnetdem_1_1webgpu_1_1_resource_manager.html", null ],
    [ "netdem::Scene", "classnetdem_1_1_scene.html", null ],
    [ "netdem::SDFCalculator", "classnetdem_1_1_s_d_f_calculator.html", null ],
    [ "netdem::Shape", "classnetdem_1_1_shape.html", [
      [ "netdem::CodedNetSDF", "classnetdem_1_1_coded_net_s_d_f.html", null ],
      [ "netdem::Cylinder", "classnetdem_1_1_cylinder.html", null ],
      [ "netdem::Ellipsoid", "classnetdem_1_1_ellipsoid.html", null ],
      [ "netdem::LevelSet", "classnetdem_1_1_level_set.html", null ],
      [ "netdem::NetSDF", "classnetdem_1_1_net_s_d_f.html", null ],
      [ "netdem::Plane", "classnetdem_1_1_plane.html", null ],
      [ "netdem::PointSphere", "classnetdem_1_1_point_sphere.html", null ],
      [ "netdem::PolySuperEllipsoid", "classnetdem_1_1_poly_super_ellipsoid.html", null ],
      [ "netdem::PolySuperQuadrics", "classnetdem_1_1_poly_super_quadrics.html", null ],
      [ "netdem::Polybezier", "classnetdem_1_1_polybezier.html", null ],
      [ "netdem::Sphere", "classnetdem_1_1_sphere.html", null ],
      [ "netdem::SphericalHarmonics", "classnetdem_1_1_spherical_harmonics.html", null ],
      [ "netdem::TriMesh", "classnetdem_1_1_tri_mesh.html", null ],
      [ "netdem::Triangle", "classnetdem_1_1_triangle.html", null ]
    ] ],
    [ "netdem::ShapeFactory", "classnetdem_1_1_shape_factory.html", null ],
    [ "netdem::Simplex", "classnetdem_1_1_simplex.html", null ],
    [ "netdem::Simulation", "classnetdem_1_1_simulation.html", null ],
    [ "netdem::SphericalVoronoi", "classnetdem_1_1_spherical_voronoi.html", null ],
    [ "netdem::STLModel", "classnetdem_1_1_s_t_l_model.html", null ],
    [ "netdem::STLReader", "classnetdem_1_1_s_t_l_reader.html", null ],
    [ "netdem::TetMesh", "classnetdem_1_1_tet_mesh.html", null ],
    [ "netdem::Voronoi", "classnetdem_1_1_voronoi.html", null ],
    [ "netdem::Wall", "classnetdem_1_1_wall.html", null ],
    [ "netdem::WallBoxPlane", "classnetdem_1_1_wall_box_plane.html", null ],
    [ "netdem::WallBoxPlate", "classnetdem_1_1_wall_box_plate.html", null ],
    [ "netdem::WebGPUManager", "classnetdem_1_1_web_g_p_u_manager.html", null ],
    [ "netdem::WebGPUWrapper", "classnetdem_1_1_web_g_p_u_wrapper.html", null ],
    [ "netdem::WSCVTSampler", "classnetdem_1_1_w_s_c_v_t_sampler.html", null ]
];