#!/usr/bin/env python3
"""
Resolve Markdown file order for PDF exports to match the site:
- Combined docs PDF: navbar left-to-right (Manual, Examples, Gallery, Download, About),
  and within each section the same doc order as the corresponding Docusaurus sidebar.
- Python API PDF: same order as the autogenerated `python-api` sidebar (Docusaurus rules).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

# Must match navbar `items` with `to: /docs/...` in docusaurus.config.ts (left to right),
# excluding API (separate PDF) and the home link.
_NAVBAR_DOCS_SECTIONS: list[tuple[str, str | None]] = [
    ("userGuideSidebar", None),
    ("examplesSidebar", None),
    ("gallerySidebar", None),
    ("downloadSidebar", "download"),
    ("aboutSidebar", None),
]

_IGNORED_MD_NAMES = {"_category_.md"}


def get_project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _extract_bracket_array(source: str, key: str) -> str | None:
    needle = f"{key}:"
    idx = source.find(needle)
    if idx == -1:
        return None
    bracket_start = source.find("[", idx)
    if bracket_start == -1:
        return None
    depth = 0
    for i in range(bracket_start, len(source)):
        c = source[i]
        if c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                return source[bracket_start + 1 : i]
    return None


def parse_sidebar_doc_ids(sidebars_ts: Path, sidebar_key: str) -> list[str]:
    """Extract ordered doc ids from an explicit sidebar (string items only)."""
    text = sidebars_ts.read_text(encoding="utf-8")
    inner = _extract_bracket_array(text, sidebar_key)
    if inner is None:
        return []
    return re.findall(r"['\"]([a-z0-9-]+/[^'\"]+)['\"]", inner)


def doc_id_to_markdown_path(docs_dir: Path, doc_id: str) -> Path:
    return docs_dir / f"{doc_id}.md"


def ordered_paths_for_combined_docs_pdf(project_root: Path) -> list[Path]:
    docs_dir = project_root / "docs"
    sidebars_ts = project_root / "sidebars.ts"
    out: list[Path] = []
    seen: set[str] = set()

    for sidebar_key, autogen_dir in _NAVBAR_DOCS_SECTIONS:
        if autogen_dir is not None:
            ids = flatten_autogenerated_doc_ids(docs_dir, autogen_dir)
        else:
            ids = parse_sidebar_doc_ids(sidebars_ts, sidebar_key)

        for doc_id in ids:
            if doc_id in seen:
                continue
            path = doc_id_to_markdown_path(docs_dir, doc_id)
            if not path.is_file():
                print(f"Warning: sidebar references missing file: {path}", flush=True)
                continue
            seen.add(doc_id)
            out.append(path)
    return out


def _read_frontmatter_raw(md: Path) -> str | None:
    text = md.read_text(encoding="utf-8")
    m = re.match(r"^---\s*\n(.*?)---\s*\n", text, re.DOTALL)
    if not m:
        return None
    return m.group(1)


def parse_sidebar_position(md: Path) -> float:
    fm = _read_frontmatter_raw(md)
    if not fm:
        return float("inf")
    m = re.search(r"^sidebar_position:\s*(\S+)\s*$", fm, re.MULTILINE)
    if not m:
        return float("inf")
    raw = m.group(1).strip().strip("\"'")
    try:
        return float(raw)
    except ValueError:
        return float("inf")


def _default_number_prefix(folder_name: str) -> float:
    """Mirror Docusaurus DefaultNumberPrefixParser (folder segment only)."""
    ignored = re.compile(r"^\d+[-_.]\d+")
    numbered = re.compile(
        r"^(?P<num>\d+)\s*[-_.]+\s*(?P<suffix>[^-_.\s].*)$"
    )
    if ignored.match(folder_name):
        return float("inf")
    match = numbered.match(folder_name)
    if not match:
        return float("inf")
    return float(int(match.group("num"), 10))


def _is_category_index_file(folder_name: str, file_base: str) -> bool:
    eligible = {
        "index",
        "readme",
        folder_name.lower(),
    }
    return file_base.lower() in eligible


def _load_category_meta(folder: Path) -> dict[str, Any] | None:
    for name in ("_category_.json", "_category_.yml", "_category_.yaml"):
        p = folder / name
        if p.is_file():
            if name.endswith(".json"):
                return json.loads(p.read_text(encoding="utf-8"))
            # Rare: skip yaml for simplicity
    return None


def markdown_path_to_doc_id(md: Path, docs_dir: Path) -> str:
    return md.relative_to(docs_dir).with_suffix("").as_posix()


def _build_fs_tree(
    base: Path,
    docs_dir: Path,
) -> dict[str, Any]:
    """Nested dict: leaf values are doc ids; dict values are subtrees (folder name -> ...)."""
    tree: dict[str, Any] = {}

    for md in sorted(base.rglob("*.md")):
        if md.name in _IGNORED_MD_NAMES:
            continue
        rel = md.relative_to(base)
        parts = list(rel.parent.parts) if rel.parent != Path(".") else []
        node: dict[str, Any] = tree
        for p in parts:
            node = node.setdefault(p, {})  # type: ignore[assignment]
        if md.name in node and isinstance(node[md.name], dict):
            raise RuntimeError(f"Conflict: {md} collides with subdirectory")
        node[md.name] = markdown_path_to_doc_id(md, docs_dir)
    return tree


def _category_link_doc_id(
    meta: dict[str, Any] | None,
    folder_name: str,
    dir_node: dict[str, Any],
    docs_dir: Path,
    autogen_root: Path,
    posix_prefix: str,
) -> str | None:
    if meta and isinstance(meta.get("link"), dict):
        link = meta["link"]
        if link.get("type") == "doc" and link.get("id"):
            raw_id = str(link["id"])
            if raw_id.startswith(f"{posix_prefix}/"):
                local = raw_id.split("/", 1)[1]
            else:
                local = raw_id
            candidates = [
                local,
                local.split("/")[-1],
            ]
            for c in candidates:
                for ext in (".md", ".MD"):
                    key = f"{c}{ext}" if c.endswith(".md") else f"{c}.md"
                    if key in dir_node and isinstance(dir_node[key], str):
                        return dir_node[key]
            path_try = autogen_root.joinpath(*local.split("/")).with_suffix(".md")
            if path_try.is_file():
                return markdown_path_to_doc_id(path_try, docs_dir)
    # Conventional category index
    for fname, val in dir_node.items():
        if not isinstance(val, str) or not fname.endswith(".md"):
            continue
        base_name = Path(fname).stem
        if _is_category_index_file(folder_name, base_name):
            return val
    return None


def _dir_to_sorted_items(
    dir_node: dict[str, Any],
    docs_dir: Path,
    autogen_root: Path,
    posix_prefix: str,
    rel_folder: str,
) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []

    for key, content in dir_node.items():
        if isinstance(content, dict):
            sub_rel = f"{rel_folder}/{key}" if rel_folder else key
            sub_meta = _load_category_meta(autogen_root / sub_rel)
            link_id = _category_link_doc_id(
                sub_meta, key, content, docs_dir, autogen_root, posix_prefix
            )
            sub_items = _dir_to_sorted_items(
                content, docs_dir, autogen_root, posix_prefix, sub_rel
            )
            filtered = [
                x for x in sub_items if not (link_id and x.get("doc_id") == link_id)
            ]
            pos: float
            if sub_meta and sub_meta.get("position") is not None:
                pos = float(sub_meta["position"])
            elif link_id:
                link_path = doc_id_to_markdown_path(docs_dir, link_id)
                pos = parse_sidebar_position(link_path)
                if pos == float("inf"):
                    pos = _default_number_prefix(key)
            else:
                pos = _default_number_prefix(key)
            items.append(
                {
                    "type": "category",
                    "sort_key": (pos, key),
                    "link_id": link_id,
                    "children": filtered,
                }
            )
        else:
            doc_id = content
            md_path = doc_id_to_markdown_path(docs_dir, doc_id)
            pos = parse_sidebar_position(md_path)
            if pos == float("inf"):
                pos = _default_number_prefix(Path(key).stem)
            items.append(
                {
                    "type": "doc",
                    "sort_key": (pos, key),
                    "doc_id": doc_id,
                }
            )
    items.sort(key=lambda x: x["sort_key"])
    return items


def _flatten_items(items: list[dict[str, Any]]) -> list[str]:
    out: list[str] = []
    for it in items:
        if it["type"] == "doc":
            out.append(it["doc_id"])
        else:
            if it.get("link_id"):
                out.append(it["link_id"])
            out.extend(_flatten_items(it["children"]))
    return out


def flatten_autogenerated_doc_ids(docs_dir: Path, dir_name: str) -> list[str]:
    """
    Doc ids under docs/{dir_name}/ in Docusaurus autogenerated sidebar order.
    """
    autogen_root = docs_dir / dir_name
    if not autogen_root.is_dir():
        return []
    tree = _build_fs_tree(autogen_root, docs_dir)
    posix_prefix = dir_name
    # Root-level _category_.json (optional) is stored in autogen_root
    items = _dir_to_sorted_items(tree, docs_dir, autogen_root, posix_prefix, "")
    return _flatten_items(items)


def ordered_paths_for_python_api_pdf(project_root: Path) -> list[Path]:
    docs_dir = project_root / "docs"
    ids = flatten_autogenerated_doc_ids(docs_dir, "python-api")
    paths = [doc_id_to_markdown_path(docs_dir, i) for i in ids]
    missing = [p for p in paths if not p.is_file()]
    if missing:
        for p in missing:
            print(f"Warning: expected API doc missing: {p}", flush=True)
        return [p for p in paths if p.is_file()]
    return paths
